# -*- coding: utf-8 -*-

#
# Autogenerated by svrkit
#

import logging
from tornado import gen
from svrkit.client import BaseClient
from app.{{ service_name }}.thf import {{ service_cls_name }}
from app.{{ service_name }}.thf import ttypes as {{ service_name }}_ttypes
from app.{{ service_name }}.thf import constants as {{ service_name }}_constants


class {{ client_cls_name }}(BaseClient, {{ service_cls_name }}.Iface):
    def __init__(self, conf_path):
        super({{ client_cls_name }}, self).__init__({{ service_cls_name }}.Client, conf_path)
    {% for method in methods %}

    @gen.coroutine
    def {{ method['name'] }}({{ method['args']|join(', ') }}):
        """
        {{ method['doc'] }}
        """
        res = yield self._remote_call('{{ method['name'] }}', {{ method['args'][1:]|join(', ') }})
        raise gen.Return(res)
    {% endfor %}

