# -*- coding: utf-8 -*-

#
# Autogenerated by svrkit
#

import time
import logging

from app.{{ service_name }}.thf.ttypes import *
from app.{{ service_name }}.thf import {{ service_cls_name }}
from svrkit.handler import BaseHandler


class {{ handler_cls_name }}(BaseHandler, {{ service_cls_name }}.Iface):
    def __init__(self):
        super({{ handler_cls_name }}, self).__init__()

    def ping(self, seq_id, ball):
        """

        Parameters:
         - seq_id
         - ball

        """
        logging.info('seq_id: %d', seq_id)
        return ball

